---
- name: Install Nginx and Deploy HTML
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy custom HTML file
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

